use jdbcinboundchanneladapter;

CREATE TABLE ITEM  (
	ID CHAR(100) NOT NULL PRIMARY KEY,
	CODE VARCHAR(100),
    DESCRIPTION VARCHAR(500),
    STATUS INT,
	CREATED_DATE DATETIME NOT NULL,
	MESSAGE_BYTES BLOB
) ENGINE=InnoDB;

--delete from item;

select count(*) from item;

select * from item where id = '19a2edfe-d3a7-424b-a613-160bf56578fa'


CREATE PROCEDURE GETITEM(IN STATUSARG int(11))
BEGIN
DECLARE ROWCOUNT int;
     SELECT * FROM ITEM WHERE STATUS = STATUSARG;
END

DROP PROCEDURE PUTITEM;

CREATE PROCEDURE PUTITEM(IN ID VARCHAR(100), IN CODE VARCHAR(100), IN DESCRIPTION VARCHAR(500), IN STATUS int(11), 
                         IN CREATED_DATE DATETIME, IN MESSAGE BLOB)
BEGIN
     INSERT INTO ITEM (ID, CODE, DESCRIPTION, STATUS, CREATED_DATE, MESSAGE_BYTES) VALUES (ID, CODE, DESCRIPTION, STATUS, CREATED_DATE, MESSAGE);
END

DROP PROCEDURE PUTANDGETITEM;

CREATE PROCEDURE PUTANDGETITEM(IN ID VARCHAR(100), IN CODE VARCHAR(100), IN DESCRIPTION VARCHAR(500), IN STATUS int(11), 
                         IN CREATED_DATE DATETIME, IN MESSAGE BLOB)
BEGIN
     INSERT INTO ITEM (ID, CODE, DESCRIPTION, STATUS, CREATED_DATE, MESSAGE_BYTES) VALUES (ID, CODE, DESCRIPTION, STATUS, CREATED_DATE, MESSAGE);
     SELECT I.* FROM ITEM I WHERE I.ID = ID;
END

call PUTANDGETITEM('0', 'code', 'description', 1, NOW(), null); 

call PUTITEM('0', 'code', 'description', 1, NOW(), null); 

select * from ITEM where '0' = '0';

select I.* from ITEM I where I.ID = '0'

select CURRENT_DATE() from item;

DROP TABLE INT_CHANNEL_MESSAGE;

CREATE TABLE INT_CHANNEL_MESSAGE (
	MESSAGE_ID CHAR(36) NOT NULL,
	GROUP_KEY CHAR(36) NOT NULL,
	CREATED_DATE BIGINT NOT NULL,
	MESSAGE_BYTES BLOB,
	REGION VARCHAR(100) NOT NULL,
	constraint INT_CHANNEL_MESSAGE_PK primary key (GROUP_KEY, MESSAGE_ID, REGION)
) ENGINE=InnoDB;

ALTER TABLE INT_CHANNEL_MESSAGE
ADD INDEX MSG_INDEX_DATE_IDX USING BTREE (CREATED_DATE ASC) ;

delete from INT_CHANNEL_MESSAGE;