/*delete from int_message_group;

delete from int_message;

select SUBSTRING(MESSAGE_BYTES, 1, 2500).MATH('e80d8f2e-85cf-4f25-bb89-5c9c3409b712') from int_message where message_id = 'e80d8f2e-85cf-4f25-bb89-5c9c3409b712';

select CAST(MESSAGE_BYTES AS CHAR(10000) CHARACTER SET utf8) from int_message where message_id = 'e80d8f2e-85cf-4f25-bb89-5c9c3409b712';



select * from int_message_group where message_id = '2d90c659-6872-4392-8cc6-bbbd587f104f';
*/

create database resequencerMessageStore;

-- Autogenerated: do not edit this file


